name: CI

on: [push]

env:
  GO_VERSION: '1.23'


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Mark source directory as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: go.mod check
        run: |
          go mod tidy
          git diff --no-patch --exit-code go.mod go.sum
          if [ $? -ne 0 ]; then
            echo "Please run go mod tidy and commit the changes."
            exit 1
          fi

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: '4.0.3'
        env:
          LOCALSTACK_CI_PROJECT: "${{ env.CI_PROJECT }}"
      - run: go test -race ./...
