name: Linting

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golang:1.23

    steps:
      - uses: actions/checkout@v3

      - name: go.mod check
        run: |
          go mod tidy
          git diff --no-patch --exit-code go.mod go.sum
          if [ $? -ne 0 ]; then
            echo "Please run go mod tidy and commit the changes."
            exit 1
          fi

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
